### ISSUE TITLE
Google Maps Tool

### ISSUE THREAD

**Issue by DaveKerswill** [ZARichardWright/BugTracker#14]
Google maps tool fails to initialise after using updater. Immediately opens then closes, I wonder if we have addressed this in the past and perhaps there wasn't any known fix as of yet. The below error pops up when opening a project which had the tool active before updating.

![Googlemaptool error](https://user-images.githubusercontent.com/101173656/157199259-8ec38134-4414-4d06-8483-56f7d6349e1e.JPG)

I recall the removal of the GoogleMapsTool.dll did the trick in the past but I see that the new update does this automatically?
Let me know if you need any other info.

**Comment by ZARichardWright** [comment]
Hi @DaveKerswill 

Please try updating GMap.NET.WindowsForms.dll as well as GMap.NET.Core.dll.

if this does not help let me know, you might need to update all your DLL but before you do that check if this helps.

cheers

**Comment by DaveKerswill** [comment]
FYI, updates of both above DLL's did the trick.

Thanks for the help

Cheers
