### ISSUE TITLE
Make a channel that increments by 1

### ISSUE THREAD

**Issue by Thys-Grob** [ZARichardWright/BugTracker#18]
@ZARichardWright 

With the new line number naming convention Magdel has introduced. Our post processing procedures is failing.
We need to re-line the names with a better and more constant incrementation, and for that, we need a channel which increments by 1 constantly, regardless of what the original line names was.

**Comment by ZARichardWright** [comment]
A new DLL Has been upoaded the drive with GX LineToChanCount makes a channel ECSLineCnt.

N:\Shared drives\NRGEX Applications\Geosoft\Current_dll

**Comment by Thys-Grob** [comment]
Thanks Richard, this looks great.
much appreciated!
