### ISSUE TITLE
ECS Grid name = Channel

### ISSUE THREAD

**Issue by Thys-Grob** [ZARichardWright/BugTracker#3]
When we Process/test/solving things in data, we grid a lot. It would go a long way if the grid we are gridding, could be equalled to the channel we are trying to grid. Channel name = grid name. 

Most ideal would be if this option could be checked with a check box perhaps (or whatever), as we don't always want to do this.
![ECS Interface](https://user-images.githubusercontent.com/99952843/154642367-916186aa-b4a7-4e77-b872-8b1b98f47353.png)
.

Also, if you can set the default of the "Use HG" check box Untoggled. Currently the default is toggled.

**Comment by ZARichardWright** [comment]
@Thys-Grob the HG toggle is easy.

Will set the Gridfile to Channel name when you change, no point in adding tickbox for this option just as much work (on your behalf) to type a new name in then deselect auto option?

**Comment by Thys-Grob** [comment]
Thanks Richard, I see what you mean, tickbox would've actually been a waste.
I've been testing this the last few days, and these small tweaks is really working nicely on our side. Thanks a lot!!

**Comment by ZARichardWright** [comment]
No worries 

Please feel free to add any other ones the more we document in the better for all.
